---
- name: init-system reload
  when: docker_config_written is changed and docker_init == 'systemd'
  become: yes
  become_user: root
  systemd:
    daemon_reload: yes

- name : launch docker...
  become: yes
  become_user: root
  service:
    name: docker
    state: started
    enabled: yes
