---
- name: resolve platform specific vars
  include_vars: '{{item}}'
  with_first_found:
    - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
    - '{{ansible_distribution}}.yml'
    - '{{ansible_os_family}}.yml'

- name: install OS dep pkgs...
  become: yes
  become_user: root
  with_items: '{{docker_os_dep_pkgs|default([])}}'
  package: name={{item}} state=present

- name: configuring package management system
  include: '{{docker_installer}}.yml'

- name: install docker-engine
  become: yes
  become_user: root
  
- name: installing PKI keys/certs
  include: pki.yml

- include: init.yml
  
- name: write /etc/profile.d/docker.sh
  become: yes
  become_user: root
  with_items:
    - etc/profile.d/docker.sh
  template: >-
    src={{item}}.j2
    dest=/{{item}}
    mode=0644

- name: launching docker daemon
  include: activate.yml
  when: docker_activate
